[tool.poetry]
name = "marginaleffects"
version = "0.0.12.1"
description = ""
authors = ["Vincent Arel-Bundock <vincent.arel-bundock@umontreal.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.0.0"
patsy = "^0.5.6"
polars = "^1.7.0"
pyarrow = "^17.0.0"
scipy = "^1.14.1"
plotnine = "^0.13.6"

[tool.poetry.group.dev.dependencies]
pandas = "^2.2.2"
pytest = "^7.4.0"
matplotlib = "^3.7.1"
typing-extensions = "^4.7.0"
pytest-xdist = "^3.6.1"
ruff = "^0.6.4"
statsmodels = "^0.14.0"
pyfixest = "^0.24.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:ConvergenceWarning',
]


[tool.ruff.lint]
extend-ignore = ["F405", "F403", "E501"]

[tool.ruff.lint.extend-per-file-ignores]
# Also ignore `E402` in all `__init__.py` files.
"__init__.py" = ["E402"]
